name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((TP|#|US)[0-9]+).+$'
          flags: 'gm'
          error: 'Commit messages must be formatted like TPxxxx or USxxxxx or #xxxxxx'
          excludeDescription: '1'
