name: 'Check Commit Message'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check_at_least_one_message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Branch Name
        id: extract_branch
        run: |
          echo "::set-output name=current_branch::${GITHUB_HEAD_REF##*/}"
          echo "::set-output name=base_branch::${GITHUB_BASE_REF##*/}"

      - name: Count Valid Messages
        id: message-validator
        run: |
          branch=${{ steps.extract_branch.outputs.current_branch }}
          base_branch=${{ steps.extract_branch.outputs.base_branch }}
          regex='^((TP|#|US)[0-9]+).+$'
          OK=0
          if [[ $base_branch == "master" ]]; then
            $(git fetch origin)
            first_commit=$(git merge-base origin/$base_branch origin/$branch)
            commits=$(git rev-list $first_commit..origin/$branch)
            for commit in $commits; do
                message=$(git cat-file commit $commit | sed '1,/^$/d')
                if [[ $message =~ $regex ]]; then
                   OK=$((OK+1))
                fi
            done
          fi
          echo "::set-output name=nr_valid_messages::${OK}"

      - name: Fail If No Message Is Valid
        run: |
          echo 'Commit messages must be formatted like TPxxxx or USxxxxx or #xxxxxx.'
          exit 1
        if: ${{ steps.message-validator.outputs.nr_valid_messages < 1 && steps.extract_branch.outputs.base_branch == "master"}}
