name: 'Validate at least one message'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check_at_least_one_message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch name
        id: extract_branch
        run: |
          echo ${GITHUB_HEAD_REF##*/}
          echo ${{ github.event.pull_request.commits_url }}
          echo ${GITHUB_BASE_REF##*/}
          echo "::set-output name=current_branch::${GITHUB_HEAD_REF##*/}"
          echo "::set-output name=master_branch::${GITHUB_BASE_REF##*/}"

      - name: Count Validated Messages
        id: message-validator
        run: |
          branch=${{ steps.extract_branch.outputs.current_branch }}
          master=${{ steps.extract_branch.outputs.master_branch }}
          regex='^((TP|#|US)[0-9]+).+$'
          OK=0
          $(git fetch origin)
          first_commit=$(git merge-base origin/master origin/$branch)
          commits=$(git rev-list $first_commit..origin/$branch)
          echo $commits
          for commit in $commits; do
              message=$(git cat-file commit $commit | sed '1,/^$/d')
              if [[ $commit_message =~ $regex ]]; then
                OK=$((OK+1))
              fi
          done
          messages=$(git log --format=%s $first_commit..origin/$branch)
          echo $messages
          for commit_message in $messages; do
              echo $commit_message
          done
          echo "::set-output name=nr_validated_messages::${OK}"

      - name: Verify at least one message matches regex
        run: |
          echo 'Commit message format must be one of "TP12345/US12345/#12345 - message".'
          exit 1
        if: ${{ steps.message-validator.outputs.nr_validated_messages < 1 }}






